name             'mongodb3'
maintainer       'Sunggun Yu'
maintainer_email 'sunggun.dev@gmail.com'
license          'Apache 2.0'
description      'Installs/Configures mongodb3'
long_description 'Installs/Configures mongodb3 fork of the one by sunggun.dev@gmail.com'
version          IO.read(File.join(File.dirname(__FILE__), 'VERSION')) rescue '0.1.0' '5.3.0'

supports 'ubuntu', '>= 12.04'
supports 'debian', '= 7.8'
supports 'redhat', '= 6.6'
supports 'centos', '= 6.8'
supports 'centos', '= 7.2'
supports 'oracle', '= 6.6'
supports 'amazon'

depends 'apt'
depends 'yum'
depends 'user'
depends 'runit', '~> 2.0.0'
